### ISSUE TITLE
Dropping a column breaks introspection

### ISSUE THREAD

**Issue by bendiy** [calebmer/postgraphql#152]
I'm testing Beta2 https://github.com/calebmer/postgraphql/pull/145

Make a table:
```
CREATE TABLE public.addr
(
  addr_id serial NOT NULL,
  addr_line1 text NOT NULL DEFAULT ' '::text,
  addr_line2 text NOT NULL DEFAULT ' '::text,
  addr_city text NOT NULL DEFAULT ' '::text,
  addr_state text NOT NULL DEFAULT ' '::text,
  addr_postalcode text NOT NULL DEFAULT ' '::text,
  addr_country text NOT NULL DEFAULT ' '::text,
  add_foo text  NOT NULL DEFAULT ' '::text,
  CONSTRAINT addr_pkey PRIMARY KEY (addr_id)
)
WITH (
  OIDS=FALSE
);
```

PostGraphQL works. 
Stop the PostGraphQL server.

Drop a column from the table:
```
ALTER TABLE public.addr DROP COLUMN add_foo;
```

Restart PostGraphQL and I get this error:
```

Error: No type was found with id 0
    at PGCatalog.assertGetType (/usr/lib/node_modules/postgraphql/build/postgres/introspection/PGCatalog.js:175:19)
    at type (/usr/lib/node_modules/postgraphql/build/postgres/inventory/type/PGObjectType.js:33:57)
    at PGObjectType.fields.Array.from.map (/usr/lib/node_modules/postgraphql/build/postgres/inventory/type/PGObjectType.js:40:23)
    at Array.map (native)
    at PGObjectType (/usr/lib/node_modules/postgraphql/build/postgres/inventory/type/PGObjectType.js:28:40)
    at PGClassObjectType (/usr/lib/node_modules/postgraphql/build/postgres/inventory/type/PGClassObjectType.js:12:9)
    at new PGCollection (/usr/lib/node_modules/postgraphql/build/postgres/inventory/collection/PGCollection.js:66:21)
    at Object.addPGCatalogToInventory (/usr/lib/node_modules/postgraphql/build/postgres/inventory/addPGCatalogToInventory.js:23:32)
    at Object.<anonymous> (/usr/lib/node_modules/postgraphql/build/postgraphql/schema/createPostGraphQLSchema.js:50:20)
    at next (native)
```

I have to drop the entire table and recreate it for the error to go away.

**Comment by calebmer** [comment]
Debugged the problem, I see the issue. Interestingly enough, from the docs on the [`pg_catalog.pg_attribute` table](https://www.postgresql.org/docs/9.6/static/catalog-pg-attribute.html) we introspect:

> In a dropped column's pg_attribute entry, atttypid is reset to zero, but attlen and the other fields copied from pg_type are still valid. This arrangement is needed to cope with the situation where the dropped column's data type was later dropped, and so there is no pg_type row anymore. attlen and the other fields can be used to interpret the contents of a row of the table.

So dropped columns still exist. For fun, the object we get back from our introspection query for that dropped column exists is:

```json
{"kind":"attribute","classId":"8687461","num":8,"name":"........pg.dropped.8........","description":null,"typeId":"0","isNotNull":false,"hasDefault":false}
```

Sure enough, the `typeId` is 0.

Thanks so much for opening an issue with such detail, if someone had just given me the `Error: No type was found with id 0` stack it would have taken me a lot of time to debug :blush:

Fixed in `2.0.0-beta.4`. Get it with:

```
npm install postgraphql@next
```

**Comment by bendiy** [comment]
@calebmer
I think you can use `att.attnum > 0 AND NOT att.attisdropped` vs. `att.attnum > 0 AND att.atttypid != 0`. I'm taking a look at the `information_schema.column_privileges` view definition and that is what postgres uses internally.
```sql
SELECT pg_get_viewdef('information_schema.column_privileges', true);
```

**Comment by calebmer** [comment]
Better idea on `att.attisdropped` :+1:

Not sure how I missed that one, I generally read the entire documentation on a `pg_catalog` table before I use it.
