### ISSUE TITLE
Naming conflict error

### ISSUE THREAD

**Issue by stlbucket** [calebmer/postgraphql#175]
9.5 database with postgis.

to repro:
-create a new db
- execute:   CREATE EXTENSION IF NOT EXISTS "postgis";

then postgraphql -c postgres://....

======================================================
Error: Naming conflict when building object. Cannot have two definitions for property 'stForce2d'.
    at entries.forEach.entry (C:\Users\Bucket\AppData\Roaming\nvm\v6.6.0\node_modules\postgraphql\build\graphql\utils\buildObject.js:40:19)
    at Array.forEach (native)
    at entriess.forEach.entries (C:\Users\Bucket\AppData\Roaming\nvm\v6.6.0\node_modules\postgraphql\build\graphql\utils\buildObject.js:35:41)
    at Array.forEach (native)
    at Object.buildObject (C:\Users\Bucket\AppData\Roaming\nvm\v6.6.0\node_modules\postgraphql\build\graphql\utils\buildObject.js:35:14)
    at fields (C:\Users\Bucket\AppData\Roaming\nvm\v6.6.0\node_modules\postgraphql\build\graphql\schema\getQueryGqlType.js:23:31)
    at resolveThunk (C:\Users\Bucket\AppData\Roaming\nvm\v6.6.0\node_modules\postgraphql\node_modules\graphql\type\definition.js:115:40)
    at defineFieldMap (C:\Users\Bucket\AppData\Roaming\nvm\v6.6.0\node_modules\postgraphql\node_modules\graphql\type\definition.js:265:18)
    at GraphQLObjectType.getFields (C:\Users\Bucket\AppData\Roaming\nvm\v6.6.0\node_modules\postgraphql\node_modules\graphql\type\definition.js:235:44)
    at C:\Users\Bucket\AppData\Roaming\nvm\v6.6.0\node_modules\postgraphql\node_modules\graphql\type\schema.js:207:27

=============================================

this sql:

SELECT  p.proname
FROM    pg_catalog.pg_namespace n
JOIN    pg_catalog.pg_proc p
ON      p.pronamespace = n.oid
WHERE   n.nspname = 'public'
AND     p.proname like 'st%2d%';

yields:

"st_makebox2d"
"st_length2d"
"st_length2dspheroid"
"st_length2d_spheroid"
"st_perimeter2d"
"st_area2d"
"st_force2d"
"st_force_2d"
"st_clipbybox2d"
"st_box2dfromgeohash"

so:
"st_force2d"
"st_force_2d"

must both be resolving to stForce2d somewhere along the way...

**Comment by ferdinandsalis** [comment]
Yes, PostGraphQL exposes field names in camelCase. Hence the problem you are describing since they both turn up to be stForce2d. Could you just change the name of field?

**Comment by calebmer** [comment]
PostGraphQL will also look in the `public` schema where PostGIS puts all of it’s helpers. I assume you don’t want to expose all of the PostGIS functions in PostGraphQL so I’d recommend specifying another schema and you can avoid this problem entirely :blush:

Like so:

```
postgraphql --schema my_schema
```

Read the [forum example tutorial](https://github.com/calebmer/postgraphql/blob/master/examples/forum/TUTORIAL.md) for more information :+1:

**Comment by stlbucket** [comment]
yes i can and will do that - i don't keep anything in the public schema so that's not an issue.  however, it would seem that postgraphql would maybe have a way to avoid such conflict with an optional warning?  no worries though.

for command line schema, how can i specify multiple schemas?

`postgraphql -c postgres://...   --schema schema_1, schema_2`

yields:

`....  Introspected Postgres schema(s) schema_1,`

the second schema doesn't appear.  help says to just separate with a comma.

**Comment by stlbucket** [comment]
ah - no spaces between schema names...

**Comment by stlbucket** [comment]
this can be closed, as far as i know.   but i would consider more gracefully handling the naming conflict.

**Comment by ferdinandsalis** [comment]
@stlbucket great to hear that it is resolved. We will think about how we can better handle this.
