### ISSUE TITLE
Exception: "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by vanwalj** [calebmer/postgraphql#176]
Hello,

This project look's really cool, unfortunately I can't get it working :(

Whenever I submit a valid query, it throw an exception 
```
"Unexpected end of JSON input"
```

It seems that the problem comme from 
`JSON.parse`
https://github.com/calebmer/postgraphql/blob/master/src/graphql/utils/idSerde.ts#L44

Module version: 2.1.0 from npm
Node version: 6.9.1 (also tested with 6.7.0)
PostgreSQL version 9.5.4

Thanks !

**Comment by ferdinandsalis** [comment]
Hi there, could you post the complete stack trace and the query you were trying to run.

**Comment by vanwalj** [comment]
Sure :)

```
http POST 0:5000/graphql query="{ user(__id: 0) { id } }"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Origin, X-Requested-With, Accept, Authorization, Content-Type, Content-Length
Access-Control-Allow-Origin: *
Access-Control-Request-Method: POST
Connection: keep-alive
Content-Length: 1494
Content-Type: application/json; charset=utf-8
Date: Fri, 21 Oct 2016 11:36:44 GMT

{
    "data": {
        "user": null
    },
    "errors": [
        {
            "locations": [
                {
                    "column": 3,
                    "line": 1
                }
            ],
            "message": "Unexpected end of JSON input",
            "stack": "SyntaxError: Unexpected end of JSON input\n    at Object.parse (native)\n    at Object.deserialize (/.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/build/graphql/utils/idSerde.js:38:52)\n    at /.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/build/graphql/schema/collection/createCollectionQueryFieldEntries.js:113:48\n    at next (native)\n    at /.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/build/graphql/schema/collection/createCollectionQueryFieldEntries.js:7:65\n    at __awaiter (/.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/build/graphql/schema/collection/createCollectionQueryFieldEntries.js:3:12)\n    at resolve (/.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/build/graphql/schema/collection/createCollectionQueryFieldEntries.js:112:20)\n    at resolveOrError (/.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/node_modules/graphql/execution/execute.js:454:12)\n    at resolveField (/.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/node_modules/graphql/execution/execute.js:445:16)\n    at /.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/node_modules/graphql/execution/execute.js:252:18"
        }
    ]
}
```

Pretiffied stack trace

```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.deserialize (/.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/build/graphql/utils/idSerde.js:38:52)
    at /.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/build/graphql/schema/collection/createCollectionQueryFieldEntries.js:113:48
    at next (native)
    at /.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/build/graphql/schema/collection/createCollectionQueryFieldEntries.js:7:65
    at __awaiter (/.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/build/graphql/schema/collection/createCollectionQueryFieldEntries.js:3:12)
    at resolve (/.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/build/graphql/schema/collection/createCollectionQueryFieldEntries.js:112:20)
    at resolveOrError (/.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/node_modules/graphql/execution/execute.js:454:12)
    at resolveField (/.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/node_modules/graphql/execution/execute.js:445:16)
    at /.nvm/versions/node/v6.9.1/lib/node_modules/postgraphql/node_modules/graphql/execution/execute.js:252:18"
```

**Comment by calebmer** [comment]
Ah, so this query:

```
{
  user(__id: 0) {
    id
  }
}
```

Expects a serialized global Relay id and not an integer :blush:

My guess is that you want to use something like:

```
{
  userById(id: 2) {
    __id
    id
  }
}
```

The `__id` selected in the query above would be what you use with `user(__id)`. This could use a better error message though, thanks for reporting :+1:

**Comment by vanwalj** [comment]
Oh, thanks !
I'm really sorry, I should definitely have read the full docs first :(

**Comment by ferdinandsalis** [comment]
@vanwalj glad to hear that solved it!
