### ISSUE TITLE
Cannot find module './catalog.js'

### ISSUE THREAD

**Issue by timbofield** [calebmer/postgraphql#28]
I'm getting the following error with all commands, 

node v5.11.0
npm 3.8.0
postgraphql@1.1.3

Maybe related to this commit 4bdc2b1ac7d912c304eeac7e10a2844b2276b14e ?

```
postgraphql --help
module.js:341
    throw err;
    ^

Error: Cannot find module './catalog.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/tim/npm/lib/node_modules/postgraphql/dist/postgres/getCatalog.js:19:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/tim/npm/lib/node_modules/postgraphql/dist/createGraphqlSchema.js:7:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by calebmer** [comment]
Thanks for the catch, fixed in `1.1.4`. The file used to be named `Catalog.js` and man, git and friends really don't like it when you try to change the case of a file 😊
