### ISSUE TITLE
Redefinition of same Relation by introspection data

### ISSUE THREAD

**Issue by martinheidegger** [calebmer/postgraphql#316]
When trying to run postgraphql against my db it exits with: 

```
Error: Relation of name 'x' already exists between head collection 'y' and tail collection 'z' in the inventory.
    at Inventory.addRelation (/home/work/postgraphql/build/interface/Inventory.js:67:19)
    at _loop_1 (/home/work/postgraphql/build/postgres/inventory/addPgCatalogToInventory.js:59:23)
    at Object.addPgCatalogToInventory (/home/work/postgraphql/build/postgres/inventory/addPgCatalogToInventory.js:67:9)
    at Object.<anonymous> (/home/work/postgraphql/build/postgraphql/schema/createPostGraphQLSchema.js:57:32)
    at step (/home/work/tslib/tslib.js:114:27)
    at Object.next (/home/work/tslib/tslib.js:95:57)
    at fulfilled (/home/work/tslib/tslib.js:85:62)
    at process._tickCallback (internal/process/next_tick.js:103:7)z
```

Not sure what exactly causes it but I am pretty sure that this is not intended, is following line really a good idea? Wouldn't it be better to check for non-equality of the relation: I.e. if the same relation already exists, no problem but if someone tries to add a relation that is syntactically different: problem?!
https://github.com/calebmer/postgraphql/blob/3e24703584bb4baaa460da589b072408020a8e1c/src/interface/Inventory.ts#L79

**Comment by benjie** [comment]
@martinheidegger Could you provide a minimal schema that reproduces the issue?
