### ISSUE TITLE
Error: Name "__id" must not begin with "__", which is reserved by GraphQL introspection.

### ISSUE THREAD

**Issue by skhro87** [calebmer/postgraphql#321]
I have tried a lot of things but always get this error message when trying to connect with postgraphql to a postgres instance.

$postgraphql -c postgres://postgres:postgres@localhost:5432/postgres -s kitchen_sink

PostGraphQL server listening on port 5000 🚀

  ‣ Connected to Postgres instance postgres://localhost:5432/postgres
  ‣ Introspected Postgres schema(s) kitchen_sink
  ‣ GraphQL endpoint served at http://localhost:5000/graphql
  ‣ GraphiQL endpoint served at http://localhost:5000/graphiql

* * *

Error: Name __id must not begin with __, which is reserved by GraphQL introspection.
    at assertValidName (/usr/lib/node_modules/postgraphql/node_modules/graphql/utilities/assertValidName.js:27:11)
    at /usr/lib/node_modules/postgraphql/node_modules/graphql/type/definition.js:328:42
    at Array.forEach (native)
    at defineFieldMap (/usr/lib/node_modules/postgraphql/node_modules/graphql/type/definition.js:327:14)
    at GraphQLInterfaceType.getFields (/usr/lib/node_modules/postgraphql/node_modules/graphql/type/definition.js:401:44)
    at /usr/lib/node_modules/postgraphql/node_modules/graphql/type/schema.js:207:27
    at typeMapReducer (/usr/lib/node_modules/postgraphql/node_modules/graphql/type/schema.js:219:7)
    at Array.reduce (native)
    at typeMapReducer (/usr/lib/node_modules/postgraphql/node_modules/graphql/type/schema.js:202:39)
    at Array.reduce (native)

The installation of postgres is fresh.
I can connect using the same connection string via psql and also via other tools.
I tried with and without specifying the schema. I run the kitchen sink sql from here http://calebmer.com/postgraphql-docs/examples/kitchen-sink/

$uname -r
4.8.13-1-ARCH

$psql --version
psql (PostgreSQL) 9.6.1

$postgraphql --version
2.5.0

**Comment by benjie** [comment]
This relates to the newly released graphql 0.9.0 which broke our dependencies - see https://github.com/calebmer/postgraphql/pull/319

Potential solutions: downgrade to graphql < 0.9 or try running postgraphql with `--classic-ids`

**Comment by skhro87** [comment]
ahhh! thanks a lot, it works with `--classic-ids` !

**Comment by benjie** [comment]
I'm leaving this open for others who find the same issue in the coming days until we get a fix out.

**Comment by calebmer** [comment]
Fixed in `3.0.0`.
