### ISSUE TITLE
no such file or directory, stat '/usr/local/lib/node_modules/postgraphql/assets/favicon.ico'

### ISSUE THREAD

**Issue by jeffcjohnson** [calebmer/postgraphql#6]
I installed with "npm install -g postgraphql" then tried to run it against a local database.  It outputs the following error and exits.
```
postgraphql postgres://localhost:5432/foo
Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/postgraphql/assets/favicon.ico'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at favicon (/usr/local/lib/node_modules/postgraphql/node_modules/serve-favicon/index.js:64:15)
    at /usr/local/lib/node_modules/postgraphql/dist/createServer.js:65:46
    at next (native)
    at step (/usr/local/lib/node_modules/postgraphql/dist/createServer.js:43:191)
    at /usr/local/lib/node_modules/postgraphql/dist/createServer.js:43:451
    at /usr/local/lib/node_modules/postgraphql/dist/createServer.js:43:99
    at createServer (/usr/local/lib/node_modules/postgraphql/dist/createServer.js:94:16)
    at /usr/local/lib/node_modules/postgraphql/dist/main.js:73:56
    at next (native)
    at step (/usr/local/lib/node_modules/postgraphql/dist/main.js:30:191)
    at /usr/local/lib/node_modules/postgraphql/dist/main.js:30:368
```

**Comment by calebmer** [comment]
Try version 1.0.4, thanks to @ryanflorence for fixing this error in #1 😊

**Comment by tryggvigy** [comment]
Can confirm this is fixed in 1.0.4

I think it's safe to close this issue

**Comment by calebmer** [comment]
Great!

@jeffcjohnson if you want to talk about your experiences with PostGraphQL, I opened up a Gitter chat here: https://gitter.im/calebmer/postgraphql

**Comment by jeffcjohnson** [comment]
Looks good, thanks for the quick fix!  I'm very excited about this :)
